script:
- git config --global user.name Root
- git config --global user.email root@boot.is
- openssl aes-256-cbc -K $encrypted_8c88444d638f_key -iv $encrypted_8c88444d638f_iv -in id_rsa.enc -out id_rsa -d
- chmod 0400 id_rsa
- ./update/$TRAVIS_BRANCH
- for BRANCH in `ls update`; do GIT_SSH_COMMAND='ssh -i id_rsa' git pull --rebase git@github.com:casey/boot.git $BRANCH; done
- for BRANCH in `ls update`; do GIT_SSH_COMMAND='ssh -i id_rsa' git push git@github.com:casey/boot.git HEAD:$BRANCH; done
